markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dylan Davidson
tagline:          'A Jekyll theme'
description:      ''
url:              http://nylad.me

author:
  name:           'Dylan Davidson'
  url:            https://twitter.com/_nylad

paginate:         5

github:
  repo:           https://github.com/dylandavidson
